package config

// Profiles is a decoded profiles document: the desired state for every
// identity on this machine.
type Profiles struct {
	// Version is the document format, so a future release can refuse a file
	// it does not understand rather than misreading it.
	Version int `yaml:"version"`

	// Profiles are the identities, in the order they were declared.
	Profiles []Profile `yaml:"profiles"`
}

// Profile is one Git identity: a key, a host alias, a commit identity, and the
// directories where that identity applies.
type Profile struct {
	// Name identifies the profile to you and on the command line.
	Name string `yaml:"name"`

	// Host is the real hostname the alias points at, such as github.com.
	Host string `yaml:"host"`

	// Alias is the ssh Host pattern used in place of Host when cloning, such
	// as github-work.
	Alias string `yaml:"alias"`

	// Key is the path to the private key for this identity. A path that does
	// not exist yet is generated by apply.
	Key string `yaml:"key"`

	// User is the commit identity written into the git config for this profile.
	User User `yaml:"user"`

	// Dirs are the directory prefixes where this identity applies, through
	// git's gitdir: conditional includes. A profile with no Dirs contributes
	// no include.
	Dirs []string `yaml:"dirs,omitempty"`

	// Options are extra ssh directives for this profile's Host stanza, such as
	// ServerAliveInterval or ProxyJump. They exist so that adopting a
	// hand-written stanza does not discard what it carried.
	Options map[string]string `yaml:"options,omitempty"`

	// Default marks the profile whose identity is written globally, applying
	// anywhere no other profile's Dirs match. At most one profile may set it.
	Default bool `yaml:"default,omitempty"`

	// ClaimHost makes this profile's stanza also answer the bare hostname, so
	// a plain git@host:owner/repo URL resolves here rather than to whatever
	// key the ssh agent offers. Only the default profile may claim it, and
	// only when asked, because it restricts every plain connection to that
	// host to this one key.
	ClaimHost bool `yaml:"claim_host,omitempty"`
}

// User is a git commit identity: the name and email that appear on a commit.
type User struct {
	// Name is the author name written to commits.
	Name string `yaml:"name"`

	// Email is the author address written to commits, and what the host
	// matches against your account to attribute them.
	Email string `yaml:"email"`
}
